Allow reading libraries from bare directories
Move to Java NIO for zip reading in inheritance map to unify the code paths
This may help speed up FART by not requiring a new zip file to be opened for each new class info request; at the cost of slightly more memory
Fix crash when attempting to read missing inheritance data for a class that throws a NoClassDefFoundError